#!/bin/bash

# Initial Settings
H=0 ; M=0 ; S=0
SOUND_PATH="$HOME/Music/Sounds/Alarm_01_Gentle.mp3"

# Parse Args
POSITIONAL_ARGS=()
while [[ $# -gt 0 ]]; do
  case $1 in
    -s|--seconds)
      S="$2"
      shift # past argument
      shift # past value
      ;;
    -m|--minutes)
      M="$2"
      shift # past argument
      shift # past value
      ;;
    -h|--hours)
      H="$2"
      shift # past argument
      shift # past value
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done

set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

# Calculate and start countdown
CD=$((60*60*$H+60*$M+$S))
if [[ $CD -eq 0 ]]; then
    CD=$((25*60));
    echo "#############################"
    echo "# Starting timer (00:25:00) #"
else 
    echo "#############################"
    printf "# Starting timer (%02d:%02d:%02d) #\n" $H $M $S
fi;
start="$(($(date +%s) + $CD))"

while [ "$start" -ge `date +%s` ]; do
    time="$(($start-`date +%s`))";
    printf '%s\r' "$(date -u -d "@$time" +%H:%M:%S)";
done
echo "Time's up!"
notify-send "Timer" "Time's up!"
mpv $SOUND_PATH
